import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      { auth: { persistSession: false } }
    )

    // Get the current user making the request
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      throw new Error('No authorization header')
    }

    const token = authHeader.replace('Bearer ', '')
    const { data: { user: currentUser }, error: userError } = await supabaseAdmin.auth.getUser(token)
    
    if (userError || !currentUser) {
      throw new Error('Unauthorized')
    }

    const { userId, email, password, fullName, employeeId, role } = await req.json()

    // Validate inputs (employeeId is optional, will be auto-generated)
    if (!userId || !email || !password || !fullName || !role) {
      throw new Error('Missing required fields')
    }

    // Validate User ID format
    if (!/^MSWIL_\d{3}$/.test(userId)) {
      throw new Error('User ID must be in format MSWIL_XXX (e.g., MSWIL_001)')
    }


    // Create email from userId
    const authEmail = `${userId}@company.local`

    // Create user in auth system
    const userMetadata: { full_name: string; employee_id?: string } = {
      full_name: fullName,
    }
    
    // Only include employee_id if provided (otherwise auto-generated by trigger)
    if (employeeId) {
      userMetadata.employee_id = employeeId
    }

    const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
      email: authEmail,
      password,
      email_confirm: true,
      user_metadata: userMetadata,
    })

    if (authError) {
      throw authError
    }

    // Assign role
    const { error: roleError } = await supabaseAdmin
      .from('user_roles')
      .insert({
        user_id: authData.user.id,
        role: role,
        assigned_by: currentUser.id,
      })

    if (roleError) {
      throw roleError
    }

    // Fetch the profile to get the auto-generated employee_id
    const { data: profileData, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('employee_id')
      .eq('id', authData.user.id)
      .single()

    if (profileError) {
      console.error('Error fetching profile:', profileError)
    }

    const finalEmployeeId = profileData?.employee_id || employeeId

    return new Response(
      JSON.stringify({ 
        success: true, 
        user: {
          id: authData.user.id,
          userId,
          email,
          fullName,
          employeeId: finalEmployeeId,
          role
        }
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'
    console.error('Error creating user:', errorMessage)
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
    )
  }
})
